"""What the status screen tells a user who wants their coding agent in the VM.

The screen renders an Access value and knows nothing about SSH. That is the
point: WSL has no SSH server, and a screen that assumed one would be a
platform branch in the UI layer.
"""
from pathlib import Path

from host.providers.lima import LimaProvider
from host.providers.wsl2 import Wsl2Provider


class FakeRunner:
    def __init__(self, stdout=b"", returncode=0):
        self.calls = []
        self._out, self._rc = stdout, returncode

    def __call__(self, argv):
        self.calls.append(argv)
        class R:
            returncode = self._rc
            stdout = self._out
            stderr = b""
        return R()


SSH_CONFIG = """\
# This SSH config file is generated by lima
Host lima-omelet-vm
  IdentityFile "/Users/you/.lima/_config/user"
  User you
  Hostname 127.0.0.1
  Port 39022
  StrictHostKeyChecking no
"""


def _provider(tmp_path, *, written=True):
    home = tmp_path / ".lima"
    if written:
        (home / "omelet-vm").mkdir(parents=True)
        (home / "omelet-vm" / "ssh.config").write_text(SSH_CONFIG)
    return LimaProvider(name="omelet-vm", runner=FakeRunner(), lima_home=home,
                        data_root=tmp_path)


def _fields(access) -> dict:
    return {f.label: f.value for f in access.fields}


def test_lima_reads_the_credentials_lima_wrote(tmp_path):
    access = _provider(tmp_path).access()
    assert _fields(access) == {
        "Host": "127.0.0.1",
        "Port": "39022",
        "User": "you",
        "Identity file": "/Users/you/.lima/_config/user",
    }
    assert not access.note


def test_lima_hands_over_a_command_that_needs_no_ssh_config_of_the_users(tmp_path):
    access = _provider(tmp_path).access()
    assert access.command == (
        f"ssh -F {tmp_path / '.lima' / 'omelet-vm' / 'ssh.config'} lima-omelet-vm")


def test_lima_falls_back_to_the_declared_port_before_the_first_boot(tmp_path):
    # ssh.config is written when the VM is created. Showing nothing until then
    # would make the screen useless exactly when a user is most lost.
    access = _provider(tmp_path, written=False).access()
    assert _fields(access)["Port"] == "39022"
    assert _fields(access)["Host"] == "127.0.0.1"
    assert access.note, "the screen must say these are defaults, not live values"
    assert "Host and Port" in access.note
    assert "User and Identity file" in access.note


def test_lima_notes_which_fields_fell_back_on_a_partial_config(tmp_path):
    # A truncated write, or a future Lima format change, can leave some
    # directives present and others missing -- not just all-or-nothing. The
    # note must say which fields are shown from a default even then, rather
    # than silently mixing real and guessed values.
    home = tmp_path / ".lima" / "omelet-vm"
    home.mkdir(parents=True)
    (home / "ssh.config").write_text(
        "Host lima-omelet-vm\n  Hostname 127.0.0.1\n  Port 41022\n")
    access = LimaProvider(name="omelet-vm", runner=FakeRunner(),
                          lima_home=tmp_path / ".lima", data_root=tmp_path).access()
    assert _fields(access)["Host"] == "127.0.0.1"
    assert _fields(access)["Port"] == "41022"
    assert access.note
    assert "User and Identity file" in access.note
    assert "what Omelet asks Lima for" not in access.note


def test_lima_parsing_is_case_insensitive_and_unquotes(tmp_path):
    home = tmp_path / ".lima" / "omelet-vm"
    home.mkdir(parents=True)
    (home / "ssh.config").write_text(
        'HOST lima-omelet-vm\n  hostname 127.0.0.1\n  PORT 40022\n'
        '  user someone\n  identityfile "/tmp/key"\n')
    access = LimaProvider(name="omelet-vm", runner=FakeRunner(),
                          lima_home=tmp_path / ".lima",
                          data_root=tmp_path).access()
    assert _fields(access)["Port"] == "40022"
    assert _fields(access)["Identity file"] == "/tmp/key"


def test_wsl2_does_not_pretend_to_have_an_ssh_server():
    access = Wsl2Provider(distro="omelet-vm", arch="amd64").access()
    assert access.command == "wsl -d omelet-vm"
    assert "ssh" not in access.command.lower()
    assert _fields(access)["Virtual machine"] == "omelet-vm"
    assert r"\\wsl$\omelet-vm\opt\omelet\projects" in _fields(access).values()


def test_both_providers_answer_with_something_a_screen_can_render(tmp_path):
    for access in (_provider(tmp_path).access(),
                   Wsl2Provider(distro="omelet-vm", arch="amd64").access()):
        assert access.headline and access.summary and access.command
        assert all(f.label and f.value for f in access.fields)
